Vs2T  : Vs_to_T_conversion.f90
	gfortran -o Vs2T Vs_to_T_conversion.f90 -fdefault-real-8 -fno-align-commons
clean1:
	rm -f Vs2T *.mod
T2Vs  : T_to_Vs_conversion.f90
	gfortran -o T2Vs T_to_Vs_conversion.f90 -fdefault-real-8 -fno-align-commons
clean2:
	rm -f T2Vs *.mod